### ISSUE TITLE
W3C trace

### ISSUE THREAD

**Issue by PeterKnealeBizCover** [zidad/MassTransit.ActivityTracing#1]
Hello,
I was wondering what is the status of this library, I am looking to do exactly as you describe (flow W3C trace context across the messages) but can't see much information specifically about the w3c context on the net. This library looks like maybe it was just a test to see if would work hypothetically? Are there other alternatives you can suggest?
Thanks
Peter

**Comment by zidad** [comment]
Yeah I need to fix it properly still, there's still problems with it :(
