### ISSUE TITLE
Publish filter mixes up header names

### ISSUE THREAD

**Issue by akosdudas** [zidad/MassTransit.ActivityTracing#3]
`OpenTracingPublishFilter.InjectHeaders` mixes up the header names at https://github.com/zidad/MassTransit.ActivityTracing/blob/master/MassTransit.ActivityTracing/ActivityTracingPublishFilter.cs#L54:

```
if (activity.TraceStateString != null)
{
   context.Headers.Set(Constants.TraceParentHeaderName, activity.TraceStateString);
}
```

The line should be

```
   context.Headers.Set(Constants.TraceStateHeaderName, activity.TraceStateString);
```

**Comment by zidad** [comment]
Hey many thanks, I still had on my list to debug this. changed it now :)

**Comment by zidad** [comment]
This library is no longer maintained, please use https://www.nuget.org/packages/OpenTelemetry.Instrumentation.MassTransit
