### ISSUE TITLE
Support for MassTransit 8.x

### ISSUE THREAD

**Issue by joh-ana** [zidad/MassTransit.ActivityTracing#5]
Wondering if this project is still alive. It currently doesn't support MassTransit 8.x.

Alternatively, are there any better ways to propagate activity tracing than this library? I did some research, but I couldn't get it done.

joh-ana

**Comment by zidad** [comment]
Hi @joh-ana, it's no longer alive, it's been superseded by this officially supported library:
https://www.nuget.org/packages/OpenTelemetry.Instrumentation.MassTransit
